-- What the data grid on Trends.MeterMonths asks the database.
-- Captured with ConnectionBus_Retrieve at TRACE, Mendix 10.24.24.119653.
-- The grid's datasource is the view entity itself; nothing else is in between.

-- 1. First page, no sort. The view entity's OQL is inlined as a derived
--    table and the grid's page size becomes LIMIT.
SELECT  "Trends.MeterMonthVE"."MeterCode", "Trends.MeterMonthVE"."Region", "Trends.MeterMonthVE"."PeriodYear", "Trends.MeterMonthVE"."MonthNo", "Trends.MeterMonthVE"."TotalKwh", "Trends.MeterMonthVE"."ReadingCount" FROM ( SELECT  "m"."metercode" AS "MeterCode", "m"."region" AS "Region", (EXTRACT(YEAR FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer AS "PeriodYear", (EXTRACT(MONTH FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer AS "MonthNo", SUM("r"."kwh") AS "TotalKwh", COUNT("r"."id") AS "ReadingCount" FROM "trends$reading" "r" INNER JOIN "trends$meter" "m" ON "m"."id" = "r"."trends$reading_meter" GROUP BY "m"."metercode", "m"."region", (EXTRACT(YEAR FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer, (EXTRACT(MONTH FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer ) "Trends.MeterMonthVE" WHERE ? != ? AND ? != ? LIMIT ?
-- runtime: Data table Trends.MeterMonthVE (15 from 216 row(s))

-- 2. After clicking the 'Total kWh' header twice: ascending, then descending.
SELECT  "Trends.MeterMonthVE"."MeterCode", "Trends.MeterMonthVE"."Region", "Trends.MeterMonthVE"."PeriodYear", "Trends.MeterMonthVE"."MonthNo", "Trends.MeterMonthVE"."TotalKwh", "Trends.MeterMonthVE"."ReadingCount" FROM ( SELECT  "m"."metercode" AS "MeterCode", "m"."region" AS "Region", (EXTRACT(YEAR FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer AS "PeriodYear", (EXTRACT(MONTH FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer AS "MonthNo", SUM("r"."kwh") AS "TotalKwh", COUNT("r"."id") AS "ReadingCount" FROM "trends$reading" "r" INNER JOIN "trends$meter" "m" ON "m"."id" = "r"."trends$reading_meter" GROUP BY "m"."metercode", "m"."region", (EXTRACT(YEAR FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer, (EXTRACT(MONTH FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer ) "Trends.MeterMonthVE" WHERE ? != ? AND ? != ? ORDER BY "Trends.MeterMonthVE"."TotalKwh" ASC LIMIT ?
-- runtime: Data table Trends.MeterMonthVE (15 from 216 row(s))
SELECT  "Trends.MeterMonthVE"."MeterCode", "Trends.MeterMonthVE"."Region", "Trends.MeterMonthVE"."PeriodYear", "Trends.MeterMonthVE"."MonthNo", "Trends.MeterMonthVE"."TotalKwh", "Trends.MeterMonthVE"."ReadingCount" FROM ( SELECT  "m"."metercode" AS "MeterCode", "m"."region" AS "Region", (EXTRACT(YEAR FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer AS "PeriodYear", (EXTRACT(MONTH FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer AS "MonthNo", SUM("r"."kwh") AS "TotalKwh", COUNT("r"."id") AS "ReadingCount" FROM "trends$reading" "r" INNER JOIN "trends$meter" "m" ON "m"."id" = "r"."trends$reading_meter" GROUP BY "m"."metercode", "m"."region", (EXTRACT(YEAR FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer, (EXTRACT(MONTH FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer ) "Trends.MeterMonthVE" WHERE ? != ? AND ? != ? ORDER BY "Trends.MeterMonthVE"."TotalKwh" DESC LIMIT ?
-- runtime: Data table Trends.MeterMonthVE (15 from 216 row(s))

-- 3. After clicking 'next page'.
SELECT  "Trends.MeterMonthVE"."MeterCode", "Trends.MeterMonthVE"."Region", "Trends.MeterMonthVE"."PeriodYear", "Trends.MeterMonthVE"."MonthNo", "Trends.MeterMonthVE"."TotalKwh", "Trends.MeterMonthVE"."ReadingCount" FROM ( SELECT  "m"."metercode" AS "MeterCode", "m"."region" AS "Region", (EXTRACT(YEAR FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer AS "PeriodYear", (EXTRACT(MONTH FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer AS "MonthNo", SUM("r"."kwh") AS "TotalKwh", COUNT("r"."id") AS "ReadingCount" FROM "trends$reading" "r" INNER JOIN "trends$meter" "m" ON "m"."id" = "r"."trends$reading_meter" GROUP BY "m"."metercode", "m"."region", (EXTRACT(YEAR FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer, (EXTRACT(MONTH FROM "r"."readat" AT TIME ZONE 'UTC' AT TIME ZONE 'UTC'))::integer ) "Trends.MeterMonthVE" WHERE ? != ? AND ? != ? ORDER BY "Trends.MeterMonthVE"."TotalKwh" DESC LIMIT ? OFFSET ?
-- runtime: Data table Trends.MeterMonthVE (15 from 216 row(s))
