#!/bin/sh
# Generated by 'mxcli init'. COMMIT THIS FILE.
#
# Run by the Claude Code SessionStart hook to make a fresh (or reaped and
# re-cloned) session ready to work: fetch mxcli if the binary is missing, then
# cache MxBuild + the runtime and provision the local database.
#
# The mxcli binary is git-ignored (~85 MB), so after an idle reap it is NOT in
# the fresh clone — which is exactly why this script fetches it rather than
# skipping when it is absent.
#
# Pin a specific mxcli with MXCLI_TAG=vX.Y.Z (default: nightly).
set -e

MPR='WorkflowExample.mpr'
TAG="${MXCLI_TAG:-nightly}"

if [ ! -x ./mxcli ]; then
  os=$(uname -s | tr 'A-Z' 'a-z')
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) arch=$(uname -m) ;;
  esac
  url="https://github.com/mendixlabs/mxcli/releases/download/${TAG}/mxcli-${os}-${arch}"
  echo "mxcli not found — downloading ${TAG} for ${os}/${arch}..."
  if ! curl -fsSL -o ./mxcli "$url"; then
    echo "Could not download mxcli from ${url}." >&2
    echo "Fetch it manually, or set MXCLI_TAG to a released version." >&2
    exit 1
  fi
  chmod +x ./mxcli
fi

# Keep .ai-context/skills/ in step with this binary. The skills are embedded in
# mxcli and written once by 'mxcli init', so upgrading the binary used to leave
# yesterday's guidance in place with no warning — and an agent reads stale
# guidance with the same confidence as current guidance. Quiet when already
# current; never fatal, since a skills refresh must not block the session.
./mxcli init --sync-skills . || true

exec ./mxcli run --local --setup --ensure-db -p "$MPR"
